In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset =pd.read_csv('Desktop/Health.csv')

In [3]:
dataset.head()

Age  HeartBeat  Systolic  Diastolic  Sugar  Alert
0   18         49        90         60     80      0
1   18         49        90         60    100      0
2   18         49        90         60    120      0
3   18         49        90         60    140      0
4   18         49        90         60    160      0

In [4]:
x= dataset.iloc[:22000,:5].values

In [5]:
type(x)

numpy.ndarray

In [6]:
x

array([[ 18,  49,  90,  60,  80],
       [ 18,  49,  90,  60, 100],
       [ 18,  49,  90,  60, 120],
       ...,
       [ 55,  79, 181, 121, 341],
       [ 55,  79, 181, 121, 361],
       [ 55,  79, 181, 121, 381]], dtype=int64)

In [7]:
y= dataset.iloc[:22000,-1:].values

In [8]:
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split           
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
import keras 
from keras.models import Sequential 
from keras.layers import Dense 

Using TensorFlow backend.


In [182]:
model=Sequential()

In [183]:
model.add(Dense(input_dim=5,init="random_uniform",activation="relu",output_dim=3))

C:\Users\Akhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=5, activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [184]:
model.add(Dense(output_dim=3,init="random_uniform",activation="relu"))

C:\Users\Akhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [185]:
model.add(Dense(output_dim=1,init="random_uniform",activation="sigmoid"))

C:\Users\Akhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [186]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [506]:
model.fit(x_train,y_train,epochs=100,batch_size=100)

Epoch 1/100
17600/17600 [==============================] - 0s 12us/step - loss: 0.0517 - acc: 0.9775
Epoch 2/100
17600/17600 [==============================] - 0s 11us/step - loss: 0.0527 - acc: 0.9774
Epoch 3/100
17600/17600 [==============================] - 0s 11us/step - loss: 0.0505 - acc: 0.9789
Epoch 4/100
17600/17600 [==============================] - 0s 12us/step - loss: 0.0503 - acc: 0.9789
Epoch 5/100
17600/17600 [==============================] - 0s 13us/step - loss: 0.0502 - acc: 0.9790
Epoch 6/100
17600/17600 [==============================] - 0s 12us/step - loss: 0.0508 - acc: 0.9788
Epoch 7/100
17600/17600 [==============================] - 0s 11us/step - loss: 0.0511 - acc: 0.9792
Epoch 8/100
17600/17600 [==============================] - 0s 11us/step - loss: 0.0496 - acc: 0.9801
Epoch 9/100
17600/17600 [==============================] - 0s 12us/step - loss: 0.0496 - acc: 0.9794
Epoch 10/100
17600/17600 [==============================] - 0s 13us/step - loss: 0.0506 - a

In [519]:
model.save("project.h5")

In [12]:
y_pred=model.predict(x_test)

In [13]:
l = len(y_pred)
l

4400

In [14]:
for i in range(l):
    if(y_pred[i] > 0.5):
        y_pred[i] =int(1)
    else:
        y_pred[i]=int(0)


In [15]:
y_pred=y_pred.astype(int)

In [16]:
y_test[8]

array([1], dtype=int64)

In [17]:
y_pred[1]

array([1])

In [11]:
from keras.models import load_model
model = load_model("project.h5")

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
matrix = confusion_matrix(y_test, y_pred)

In [20]:
matrix

array([[ 152,   72],
       [  17, 4159]], dtype=int64)

In [21]:
pred=model.predict(np.array([[35,74,90,70,80]]))
if(pred > 0.5):
    pred =int(1)
else:
    pred =int(0)
pred    

1

In [22]:
y_test

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [23]:
y_pred


array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [24]:
x_test[0]

array([ 55,  71, 125,  85, 200], dtype=int64)